[rank: 0] Global seed set to 42
wandb: Currently logged in as: usainzg. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in logs/wandb/run-20230523_204100-2zhv733j
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run resnet34-tucker-0.3-1684867248.418098
wandb: ⭐️ View project at https://wandb.ai/usainzg/td-compression
wandb: 🚀 View run at https://wandb.ai/usainzg/td-compression/runs/2zhv733j
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs/tensorboard/resnet34-tucker-0.3-1684867248.418098
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name  | Type             | Params
-------------------------------------------
0 | model | ResNet           | 13.6 M
1 | loss  | CrossEntropyLoss | 0     
-------------------------------------------
13.6 M    Trainable params
0         Non-trainable params
13.6 M    Total params
54.364    Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
`Trainer.fit` stopped: `max_epochs=50` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
SLURM auto-requeueing enabled. Setting signal handlers.
wandb: Waiting for W&B process to finish... (success).
wandb: - 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: \ 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: | 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: / 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: - 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: \ 0.005 MB of 0.005 MB uploaded (0.000 MB deduped)wandb: 
wandb: Run history:
wandb:               epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:       test_accuracy ▁
wandb:           test_loss ▁
wandb:      train_accuracy ▁▄▆▅▅▆▆▆▆▆▇▇▇▇▆▇▇▇▇▇▇▇█▇▇▇██▇▇▇███▇████▇
wandb:          train_loss █▆▄▄▄▃▃▃▃▃▂▂▂▂▂▂▂▂▂▂▁▁▁▂▂▂▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb: trainer/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:        val_accuracy ▁▃▄▅▆▆▆▆▇▇▇▇▇▇▇▆▇▇█▇█▇▇▇██▇█████████████
wandb:            val_loss █▆▅▄▃▃▃▃▂▂▂▂▁▂▂▃▂▁▁▂▁▁▂▂▁▁▂▁▁▁▁▂▁▁▂▂▁▁▁▁
wandb: 
wandb: Run summary:
wandb:               epoch 50
wandb:       test_accuracy 0.9068
wandb:           test_loss 0.3941
wandb:      train_accuracy 0.94444
wandb:          train_loss 0.09592
wandb: trainer/global_step 17600
wandb:        val_accuracy 0.8992
wandb:            val_loss 0.37529
wandb: 
wandb: 🚀 View run resnet34-tucker-0.3-1684867248.418098 at: https://wandb.ai/usainzg/td-compression/runs/2zhv733j
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: logs/wandb/run-20230523_204100-2zhv733j/logs
Exception in thread NetStatThr:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 260, in check_network_status
    self._loop_check_status(
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 216, in _loop_check_status
    local_handle = request()
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 795, in deliver_network_status
    return self._deliver_network_status(status)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 601, in _deliver_network_status
    return self._deliver_record(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 560, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
