[rank: 0] Global seed set to 42
wandb: Currently logged in as: usainzg. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.15.3
wandb: Run data is saved locally in logs/wandb/run-20230523_201224-x7co25iv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run vgg11-tucker-0.8-1684865538.1726272
wandb: ⭐️ View project at https://wandb.ai/usainzg/td-compression
wandb: 🚀 View run at https://wandb.ai/usainzg/td-compression/runs/x7co25iv
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: logs/tensorboard/vgg11-tucker-0.8-1684865538.1726272
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [6]

  | Name  | Type             | Params
-------------------------------------------
0 | model | VGG              | 7.4 M 
1 | loss  | CrossEntropyLoss | 0     
-------------------------------------------
7.4 M     Trainable params
0         Non-trainable params
7.4 M     Total params
29.582    Total estimated model params size (MB)
SLURM auto-requeueing enabled. Setting signal handlers.
`Trainer.fit` stopped: `max_epochs=50` reached.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [6]
SLURM auto-requeueing enabled. Setting signal handlers.
wandb: Waiting for W&B process to finish... (success).
wandb: 
wandb: Run history:
wandb:               epoch ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:       test_accuracy ▁
wandb:           test_loss ▁
wandb:      train_accuracy ▁▃▆▅▅▆▆▅▆▅▇▇▇▆▆▆▅▇█▇▇▇▇▇▆▇█▇▇▇▇███▇██▇█▇
wandb:          train_loss █▆▄▅▄▃▃▄▃▄▂▂▃▃▃▄▄▂▁▂▂▂▂▂▃▂▂▂▂▂▂▁▁▁▂▁▁▂▁▁
wandb: trainer/global_step ▁▁▁▁▂▂▂▂▂▃▃▃▃▃▃▄▄▄▄▄▅▅▅▅▅▅▆▆▆▆▆▇▇▇▇▇▇███
wandb:        val_accuracy ▁▃▄▄▄▅▅▆▆▇▆▇▇▇▇▇▇▆▇▇▇▇▇▇▇▇▇█▇██▇████████
wandb:            val_loss █▆▅▅▅▄▄▃▃▂▃▂▂▂▂▂▂▃▂▂▂▂▂▂▂▂▂▂▁▁▂▂▂▁▁▁▁▁▁▂
wandb: 
wandb: Run summary:
wandb:               epoch 50
wandb:       test_accuracy 0.8671
wandb:           test_loss 0.45147
wandb:      train_accuracy 0.88889
wandb:          train_loss 0.22317
wandb: trainer/global_step 17600
wandb:        val_accuracy 0.8618
wandb:            val_loss 0.47676
wandb: 
wandb: 🚀 View run vgg11-tucker-0.8-1684865538.1726272 at: https://wandb.ai/usainzg/td-compression/runs/x7co25iv
wandb: Synced 5 W&B file(s), 0 media file(s), 0 artifact file(s) and 0 other file(s)
wandb: Find logs at: logs/wandb/run-20230523_201224-x7co25iv/logs
Exception in thread ChkStopThr:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 278, in check_stop_status
    self._loop_check_status(
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/wandb_run.py", line 216, in _loop_check_status
    local_handle = request()
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 787, in deliver_stop_status
    return self._deliver_stop_status(status)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 585, in _deliver_stop_status
    return self._deliver_record(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 560, in _deliver_record
    handle = mailbox._deliver_record(record, interface=self)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/mailbox.py", line 455, in _deliver_record
    interface._publish(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/interface/interface_sock.py", line 51, in _publish
    self._sock_client.send_record_publish(record)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 221, in send_record_publish
    self.send_server_request(server_req)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 155, in send_server_request
    self._send_message(msg)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 152, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/pscratch/usainz/projects/tn-comp/td-compression/.venv/lib/python3.8/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
